name: CI and Test

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build
        run: go generate ./...

      - name: Install go/vulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Go vulncheck
        run: govulncheck ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -v -race -p=1 ./...